# Load in NumPy

In [1]:
import numpy as np

# The Basics

In [7]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get dimension
a.ndim

1

In [5]:
# Get shape
b.shape

(2, 3)

In [8]:
# Get Type
a.dtype

dtype('int16')

In [9]:
# Get size
a.itemsize

2

In [12]:
# Get total size
#a.size * a.itemsize
a.nbytes

6

In [13]:
b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


# Accessing/Changing specific elements, rows, columns, etc

In [15]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get a specific element [r, c]
a[1,5]

13

In [18]:
a[1,-2]

13

In [19]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [21]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [22]:
a[0,1:-1:2]

array([2, 4, 6])

In [24]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [25]:
a[:,2] = 5
print (a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [26]:
a[:,2] = [1,2]
print (a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
*3-d example

In [28]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
# Get specific element (work outside in)
b[0,1,1]

4

In [30]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [31]:
b[:,0,0]

array([1, 5])

# Replace

In [35]:
b[:,1,:]

array([[9, 9],
       [8, 8]])

In [33]:
# replace
b[:,1,:] =[[9,9],[8,8]]

In [34]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [38]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [39]:
a[:, 2] = 20
print(a)

[[ 1  2 20  4  5]
 [ 6  7 20  9 10]]


Initializing Different Types of Arrays

In [40]:
# ALL 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [45]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [47]:
# ALL 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [48]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [51]:
# Any other number (full_like)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [52]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [56]:
# Random decimal numnbers
np.random.rand(4,2)

array([[0.8650312 , 0.39916653],
       [0.50593074, 0.76727627],
       [0.03420693, 0.94721485],
       [0.69596408, 0.81007402]])

In [57]:
# Random decimal numnbers
np.random.rand(4,2,3)

array([[[0.29452484, 0.24145594, 0.20891778],
        [0.68732011, 0.93606807, 0.96346148]],

       [[0.51676102, 0.80306211, 0.87429251],
        [0.63708249, 0.86919398, 0.31279558]],

       [[0.16429443, 0.98685996, 0.05977349],
        [0.4387517 , 0.5943501 , 0.93646956]],

       [[0.7769237 , 0.93880899, 0.43881737],
        [0.42981548, 0.43619309, 0.42333198]]])

In [58]:
np.random.random_sample(a.shape)

array([[0.24427212, 0.54036483, 0.58329387, 0.14918072, 0.86920015],
       [0.46927536, 0.15456805, 0.63197997, 0.56440575, 0.8607581 ]])

In [60]:
# Random integer values
np.random.randint(7)

4

In [61]:
np.random.randint(7, size=(3,3))

array([[3, 1, 5],
       [3, 2, 0],
       [4, 1, 4]])

In [62]:
np.random.randint(4,7, size=(3,3))

array([[5, 4, 6],
       [4, 5, 4],
       [6, 5, 6]])

In [63]:
np.random.randint(-4,8, size=(3,3))

array([[-1, -1, -1],
       [ 3,  7,  7],
       [-2,  0,  4]])

In [64]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
# Repeat an array 
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [69]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [71]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


Matrix exercise

In [72]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [74]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [75]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [76]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [77]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [79]:
output = np.zeros((7,7))

z = np.ones((5, 5))
z[2, 2] = 5

output[1:-1, 1:-1] = z
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


##### Be careful when copying arrays!!!

In [80]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [82]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)

[100   2   3]


In [83]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [84]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


In [85]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


In [87]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20
print(a)

[ 1  2 20  4  5]


# Mathematics
https://numpy.org/doc/stable/reference/routines.math.html

In [89]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [90]:
a + 2

array([3, 4, 5, 6])

In [91]:
a * 2

array([2, 4, 6, 8])

In [92]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [93]:
a += 2
a

array([3, 4, 5, 6])

In [95]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [99]:
b = np.array([1,0,1,0])
a * b

array([3, 0, 5, 0])

In [96]:
a ** 2

array([ 9, 16, 25, 36])

In [97]:
# Take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [98]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

#### Linear Algebra
https://numpy.org/doc/stable/reference/routines.linalg.html

In [101]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [102]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [103]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
#### Statistics

In [104]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
np.min(stats, axis=0)

array([1, 2, 3])

In [108]:
np.min(stats)

1

In [106]:
np.max(stats)

6

In [109]:
np.max(stats, axis=1)

array([3, 6])

In [110]:
np.sum(stats)

21

In [111]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [113]:
import numpy as np

a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()
print(b)

15


#### Reorganizing arrays

In [114]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [115]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before.shape)

(2, 4)


In [116]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [117]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [118]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [120]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [121]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v1,v2,v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [122]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [124]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [125]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
h2

array([[0., 0.],
       [0., 0.]])

In [126]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (941666502.py, line 1)

In [128]:
a = np.ones((2, 4))
b = a.reshape((4, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


#### Miscellaneous

Load data from file

In [2]:
pip install requests


Note: you may need to restart the kernel to use updated packages.


In [3]:
import requests


In [8]:
import requests

# URL for fetching the raw content of the .txt file
url = 'https://raw.githubusercontent.com/OYanez85/Numpy_freecodecamp/develop/data.txt'

# Making a GET request to fetch the content of the URL
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # The content of the response is the content of the .txt file
    content = response.text
    
    # Now you can use 'content' as needed, e.g., print it, process it, etc.
    print(content)
else:
    print(f"Failed to fetch the file. Status code: {response.status_code}")


1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5
3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12
1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88



In [11]:
# Importing the NumPy library with the alias 'np'
import numpy as np

# Assuming you want to load data from a URL, you first need to fetch the content
# For demonstration, let's use the requests library to download the .txt file
import requests

# URL of the raw content of the .txt file
url = 'https://raw.githubusercontent.com/OYanez85/Numpy_freecodecamp/develop/data.txt'

# Making a GET request to fetch the content of the URL
response = requests.get(url)

# Ensure the request was successful
if response.status_code == 200:
    # Convert the content of the response to a string and split it into lines
    content = response.content.decode('utf-8')
    
    # Use StringIO to convert the string content into a file-like object
    # This allows np.genfromtxt to treat it as a file
    from io import StringIO
    content_file = StringIO(content)
    
    # Now you can use np.genfromtxt to read the data into a NumPy array
    filedata = np.genfromtxt(content_file, delimiter=',')
    
    # Now 'filedata' is a NumPy array containing the data from 'data.txt'
    print(filedata)
else:
    print(f"Failed to fetch the file. Status code: {response.status_code}")


[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [12]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [13]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [14]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [15]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### Boolean Masking and Advanced indexing

In [16]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [17]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

## You can index with a list in Numpy

In [18]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [19]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [20]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [21]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [23]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [24]:
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [ ]:
# Exercise

In [25]:
# Creating a matrix of five columns and six rows with numbers in order from 1 to 30
matrix = np.arange(1, 31).reshape(6, 5)

matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [31]:
# Correct indexing to capture the values 11, 12, 16, and 17
selected_elements = matrix[2:4, 0:2]
print(selected_elements)

[[11 12]
 [16 17]]


In [32]:
# Correct indexing to capture the values 2, 8, 14, and 20
selected_elements = matrix[[0,1,2,3], [1,2,3,4]]
print(selected_elements)

[ 2  8 14 20]


In [33]:
# Correct indexing to capture the values 4, 5, 24, 25, 29, and 30
selected_elements = matrix[[0,4,5], 3:]
print(selected_elements)

[[ 4  5]
 [24 25]
 [29 30]]


In [35]:
# Creating a matrix with the specified numbers
matrix = np.array([[29, 97, 32, 100, 45],
                   [15, 88, 5, 75, 22]])

matrix



array([[ 29,  97,  32, 100,  45],
       [ 15,  88,   5,  75,  22]])

In [37]:
# Given the previously defined matrix
matrix = np.array([[29, 97, 32, 100, 45],
                   [15, 88, 5, 75, 22]])

# Applying the condition to select elements less than 50
output = matrix[matrix < 50]

print(output)


[29 32 45 15  5 22]
